Traceback (most recent call last):
  File "C:\Users\pzysk\PycharmProjects\github\debugging\debugging.py", line 6, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
